/**
 * NL Eats, graph data model + pure helpers.
 *
 * This is the single fixed-shape contract the chart reads. The SINGLE SOURCE OF
 * TRUTH for the numbers is the Google Sheet; `data/graph-data.csv` is its one
 * committed snapshot (regenerated by `npm run sync:data`), parsed into this shape
 * by `lib/parse-sheet-csv.ts` and surfaced server-side via `lib/seed-data.ts`.
 * This file holds only the types, the code-managed `graphMeta`, and the pure
 * helpers, never hand-typed data.
 *
 * Every figure traces to a citation key (the `source` field) and was
 * independently verified on 2026-07-15. Confidence: `estimate: false` = firm
 * (official/primary source); `estimate: true` = derived/estimated and MUST render
 * an "estimate" affordance + method (see `note`).
 *
 * CRA figures (CCB / CGEB / NLCB / NL Income Supplement) were confirmed directly
 * against the canada.ca pages in a real browser (canada.ca 403-blocks automated
 * fetchers, so re-check them in a browser before each public release).
 */

export type Money = number; // CAD, per month

export interface LineItem {
  /** stable id, e.g. "basic", "housing", "food" (food row uses "food") */
  key: string;
  /** display label */
  label: string;
  /** monthly $ */
  amount: Money;
  /** true → render with an "estimate" marker + surface `note` */
  estimate: boolean;
  /** citation key, e.g. "gov-nl-is-2025" */
  source: string;
  /**
   * Optional method / provenance detail (matches the Google-Sheet `notes` column).
   * Required in spirit for every `estimate: true` item so the UI can explain the
   * method in a tooltip.
   */
  note?: string;
}

export type HouseholdId = "single" | "couple" | "family4";

export interface Household {
  id: HouseholdId;
  /** "Single adult", "Couple", "Family of four" */
  label: string;
  /** stacked income segments (money the household receives) */
  income: LineItem[];
  /** stacked essential-cost segments; `costs[0]` is food (NFB) */
  costs: LineItem[];
  /** MBM poverty line ÷ 12 → chart <ReferenceLine> */
  povertyLineMonthly: Money;
  /** citation key for the poverty line */
  povertyLineSource: string;
  /** true → the poverty line itself is derived/estimated */
  povertyLineEstimate?: boolean;
}

export interface GraphMeta {
  currency: "CAD";
  period: "monthly";
  /** provincial income-support rate year (NL Sept-2025 enhancement) */
  incomeYear: number;
  /** federal benefit year (CCB / CGEB / NL programs benefit year) */
  federalYear: number;
  /** Nutritious Food Basket year */
  foodYear: number;
  /** Market Basket Measure poverty-benchmark year */
  povertyYear: number;
  /** ISO date this dataset was last verified */
  lastUpdated: string;
  /** weekly→monthly convention used for food figures */
  monthlyFactor: 4 | 4.33;
  /**
   * True when the payload is the committed CSV fallback because the live Google
   * Sheet was unreachable. Set by the Route Handler, never on the shared
   * `graphMeta`; the client shows a non-blocking "last-known figures" notice.
   */
  stale?: boolean;
}

export interface GraphData {
  meta: GraphMeta;
  households: Household[];
}

/**
 * Dataset `meta`. This is NOT a per-row Google-Sheet field (the Sheet has no meta
 * columns), so it lives in code and is bumped on a data refresh. Applied by the
 * CSV parser (`lib/parse-sheet-csv.ts`) as the default `meta` for every payload.
 */
export const graphMeta: GraphMeta = {
  currency: "CAD",
  period: "monthly",
  incomeYear: 2025, // NL Income-Support rates: Sept-2025 enhancement
  federalYear: 2026, // federal benefit year (CCB/CGEB 2026-27)
  foodYear: 2024, // Nutritious Food Basket
  povertyYear: 2024, // Maytree "Welfare in Canada" / MBM
  lastUpdated: "2026-07-15",
  monthlyFactor: 4.33,
};

// ── pure helpers (exported so the Vitest suites can import & assert them) ──

/** Sum the monthly amounts of a set of line items. */
export function sumLineItems(items: LineItem[]): Money {
  return items.reduce((total, item) => total + item.amount, 0);
}

/**
 * Shortfall = total income − total essential costs. Negative → deficit
 * (status/red styling on the client).
 *
 * Labelling caveat: `costs` is currently food-only while `income` includes a
 * housing/rental line earmarked for rent, so this value is "what's left AFTER
 * healthy food, for rent + heat + everything else", NOT a disposable surplus.
 * The UI must frame it that way, never a bare "money left".
 */
export function computeShortfall(income: LineItem[], costs: LineItem[]): Money {
  return sumLineItems(income) - sumLineItems(costs);
}

/** Convenience lookup by household id. */
export function getHousehold(
  data: GraphData,
  id: HouseholdId,
): Household | undefined {
  return data.households.find((h) => h.id === id);
}

/** Deep income poverty threshold: below 75% of the Market Basket Measure line. */
export const DEEP_POVERTY_FRACTION = 0.75;

/**
 * A household's total income as a share of its own MBM poverty line (1 = at the
 * line). This is the axis of the cross-household comparison chart and mirrors
 * Maytree's "welfare income vs. the Market Basket Measure" framing: the income
 * total includes the rent-earmarked housing benefit, exactly as Maytree counts
 * total welfare income. Returns 0 when the line is non-positive (guards ÷0).
 */
export function povertyLineShare(household: Household): number {
  if (household.povertyLineMonthly <= 0) return 0;
  return sumLineItems(household.income) / household.povertyLineMonthly;
}

/**
 * Count, across the modelled households, how many fall below the MBM poverty line
 * and how many are in *deep* poverty (< 75% of the line). Derived, never hardcoded,
 * so the on-page poverty claim can't drift from the households actually shown.
 * Exported for the Sources & methodology copy and for tests.
 */
export function povertyStats(households: Household[]): {
  total: number;
  belowLine: number;
  deepPoverty: number;
} {
  const belowLine = households.filter(
    (h) => sumLineItems(h.income) < h.povertyLineMonthly,
  ).length;
  const deepPoverty = households.filter(
    (h) =>
      sumLineItems(h.income) < DEEP_POVERTY_FRACTION * h.povertyLineMonthly,
  ).length;
  return { total: households.length, belowLine, deepPoverty };
}
