/**
 * NL Eats, graph data model + pure helpers.
 *
 * This is the single fixed-shape contract the chart reads. The SINGLE SOURCE OF
 * TRUTH for the numbers is the Google Sheet; `data/graph-data.csv` is its one
 * committed snapshot (regenerated by `npm run sync:data`), parsed into this shape
 * by `lib/parse-sheet-csv.ts` and surfaced server-side via `lib/seed-data.ts`.
 * This file holds only the types, the code-managed `graphMeta`, and the pure
 * helpers — no hand-typed data (the former `mockGraphData` literal is retained,
 * commented out below, for history).
 *
 * Every figure traces to a citation key (the `source` field) and was
 * independently verified on 2026-07-13. Confidence: `estimate: false` = firm
 * (official/primary source); `estimate: true` = derived/estimated and MUST render
 * an "estimate" affordance + method (see `note`).
 *
 * CRA figures (CCB / CGEB / NLCB / NL Income Supplement) rest on verbatim
 * search-extraction plus convergent secondary sources because canada.ca 403-blocks
 * automated fetchers; re-check them in a browser before a public release.
 */

export type Money = number; // CAD, per month

export interface LineItem {
  /** stable id, e.g. "basic", "housing", "food" (food row uses "food") */
  key: string;
  /** display label */
  label: string;
  /** monthly $ */
  amount: Money;
  /** true → render with an "estimate" marker + surface `note` */
  estimate: boolean;
  /** citation key, e.g. "gov-nl-is-2025" */
  source: string;
  /**
   * Optional method / provenance detail (matches the Google-Sheet `notes` column).
   * Required in spirit for every `estimate: true` item so the UI can explain the
   * method in a tooltip.
   */
  note?: string;
}

export type HouseholdId = "single" | "couple" | "family4";

export interface Household {
  id: HouseholdId;
  /** "Single adult", "Couple", "Family of four" */
  label: string;
  /** stacked income segments (money the household receives) */
  income: LineItem[];
  /** stacked essential-cost segments; `costs[0]` is food (NFB) */
  costs: LineItem[];
  /** MBM poverty line ÷ 12 → chart <ReferenceLine> */
  povertyLineMonthly: Money;
  /** citation key for the poverty line */
  povertyLineSource: string;
  /** true → the poverty line itself is derived/estimated */
  povertyLineEstimate?: boolean;
}

export interface GraphMeta {
  currency: "CAD";
  period: "monthly";
  /** provincial income-support rate year (NL Sept-2025 enhancement) */
  incomeYear: number;
  /** federal benefit year (CCB / CGEB / NL programs benefit year) */
  federalYear: number;
  /** Nutritious Food Basket year */
  foodYear: number;
  /** Market Basket Measure poverty-benchmark year */
  povertyYear: number;
  /** ISO date this dataset was last verified */
  lastUpdated: string;
  /** weekly→monthly convention used for food figures */
  monthlyFactor: 4 | 4.33;
  /**
   * True when the payload is the committed CSV fallback because the live Google
   * Sheet was unreachable. Set by the Route Handler, never on the shared
   * `graphMeta`; the client shows a non-blocking "last-known figures" notice.
   */
  stale?: boolean;
}

export interface GraphData {
  meta: GraphMeta;
  households: Household[];
}

// ── former mock payload ──
//
// Superseded by data/graph-data.csv (the single source of truth), parsed via
// lib/seed-data.ts. The hand-typed household literals and `mockGraphData` below
// are kept commented for history — do not delete.
/*
const single: Household = {
  id: "single",
  label: "Single adult",
  income: [
    {
      key: "basic",
      label: "Basic Income Support",
      amount: 561,
      estimate: false,
      source: "gov-nl-is-2025",
      note: "Per adult, effective Sept 2025 enhancement.",
    },
    {
      key: "housing",
      label: "Housing / rental support",
      amount: 522,
      estimate: false,
      source: "gov-nl-is-overview",
      note: "Up to this maximum (single living alone); reimburses rent up to the cap.",
    },
    {
      key: "fuel",
      label: "Fuel supplement",
      amount: 71,
      estimate: false,
      source: "gov-nl-fuel",
      note: "Island rate ($132 in Labrador); policy manual rev. 2016, unchanged by the Sept-2025 enhancement.",
    },
    {
      key: "cgeb",
      label: "Canada Groceries & Essentials Benefit",
      amount: 57,
      estimate: false,
      source: "cra-cgeb",
      note: "Formerly the GST/HST credit; renamed & revalued eff. July 2026 (max $679/yr single). Re-check on canada.ca in a browser before public release.",
    },
  ],
  costs: [
    {
      key: "food",
      label: "Healthy food (Nutritious Food Basket)",
      amount: 450,
      estimate: true,
      source: "foodfirst-nfb-2024",
      note: "Estimate: NL publishes no single-adult food basket. Derived from the 2024 family-of-four NFB ($336/wk provincial avg) via a reference-adult share (~26% of the basket) + a ~20% one-person surcharge, ×4.33 (calendar month), not a flat ÷4. Food First NL to supply the household figure.",
    },
  ],
  povertyLineMonthly: 2247, // $26,970/yr ÷ 12 (single, employable)
  povertyLineSource: "maytree-nl-2024",
  povertyLineEstimate: false,
};

const couple: Household = {
  id: "couple",
  label: "Couple",
  income: [
    {
      key: "basic",
      label: "Basic Income Support",
      amount: 1122,
      estimate: false,
      source: "gov-nl-is-2025",
      note: "$561 × 2 adults, effective Sept 2025.",
    },
    {
      key: "housing",
      label: "Housing / rental support",
      amount: 598,
      estimate: false,
      source: "gov-nl-is-overview",
      note: "Up to this maximum ($299 per adult).",
    },
    {
      key: "fuel",
      label: "Fuel supplement",
      amount: 71,
      estimate: false,
      source: "gov-nl-fuel",
      note: "Per household, Island rate ($132 in Labrador).",
    },
    {
      key: "cgeb",
      label: "Canada Groceries & Essentials Benefit",
      amount: 74,
      estimate: false,
      source: "cra-cgeb",
      note: "Formerly the GST/HST credit; max $890/yr couple. Re-check on canada.ca in a browser before public release.",
    },
  ],
  costs: [
    {
      key: "food",
      label: "Healthy food (Nutritious Food Basket)",
      amount: 820,
      estimate: true,
      source: "foodfirst-nfb-2024",
      note: "Estimate: no published NL couple food basket. Derived from the 2024 family-of-four NFB via two adult shares (~51% of the basket) + a ~10% two-person surcharge, ×4.33, not a flat scaling of the family basket. Food First NL to supply the figure.",
    },
  ],
  // Maytree does NOT model a couple-with-no-children household; this MBM line is
  // derived by √-of-household-size scaling, so it is flagged as an estimate.
  povertyLineMonthly: 3179, // ~$38,142/yr ÷ 12
  povertyLineSource: "maytree-nl-2024",
  povertyLineEstimate: true,
};

const family4: Household = {
  id: "family4",
  label: "Family of four",
  income: [
    {
      key: "basic",
      label: "Basic Income Support",
      amount: 1122,
      estimate: false,
      source: "gov-nl-is-2025",
      note: "Couple with dependent children, effective Sept 2025.",
    },
    {
      key: "housing",
      label: "Housing / rental support",
      amount: 598,
      estimate: false,
      source: "gov-nl-is-overview",
      note: "Up to this maximum ($299 per adult).",
    },
    {
      key: "fuel",
      label: "Fuel supplement",
      amount: 71,
      estimate: false,
      source: "gov-nl-fuel",
      note: "Per household, Island rate ($132 in Labrador).",
    },
    {
      key: "nlcb",
      label: "NL Child Benefit (2 children)",
      amount: 324.17,
      estimate: false,
      source: "gov-nl-nlcb",
      note: "$157.33 (1st child) + $166.83 (2nd), effective July 1 2026.",
    },
    {
      key: "ccb",
      label: "Canada Child Benefit (2 children)",
      amount: 1147,
      estimate: true,
      source: "cra-ccb",
      note: "Estimate: age-dependent. 2026–27 max $573.58/mo per child aged 6–17 (2 × $573.58 ≈ $1,147); a child under 6 raises it to $679.75/mo. Re-check on canada.ca in a browser before public release.",
    },
    {
      key: "cgeb",
      label: "Canada Groceries & Essentials Benefit",
      amount: 113,
      estimate: false,
      source: "cra-cgeb",
      note: "Formerly the GST/HST credit; max couple $890 + $234/child = $1,358/yr.",
    },
    {
      key: "nl-income-supplement",
      label: "NL Income Supplement",
      amount: 88,
      estimate: true,
      source: "cra-nl-programs",
      note: "Estimate: max $589 (couple) + $231/child = $1,051/yr, paid quarterly.",
    },
  ],
  costs: [
    {
      key: "food",
      label: "Healthy food (Nutritious Food Basket)",
      amount: 1455,
      estimate: false,
      source: "foodfirst-nfb-2024",
      note: "2024 provincial average, family of four: $336/wk × 4.33 (calendar month). Food First NL's own published monthly figure uses ×4 ($1,344/mo).",
    },
  ],
  povertyLineMonthly: 4495, // $53,940/yr ÷ 12 (couple + 2 children)
  povertyLineSource: "maytree-nl-2024",
  povertyLineEstimate: false,
};
*/

/**
 * Dataset `meta`. This is NOT a per-row Google-Sheet field (the Sheet has no meta
 * columns), so it lives in code and is bumped on a data refresh. Shared by the mock
 * AND the CSV parser (`lib/parse-sheet-csv.ts`) so they agree.
 */
export const graphMeta: GraphMeta = {
  currency: "CAD",
  period: "monthly",
  incomeYear: 2025, // NL Income-Support rates: Sept-2025 enhancement
  federalYear: 2026, // federal benefit year (CCB/CGEB 2026-27)
  foodYear: 2024, // Nutritious Food Basket
  povertyYear: 2024, // Maytree "Welfare in Canada" / MBM
  lastUpdated: "2026-07-14",
  monthlyFactor: 4.33,
};

// Superseded by data/graph-data.csv + lib/seed-data.ts (single source of truth).
// Kept for history — do not delete.
// export const mockGraphData: GraphData = {
//   meta: graphMeta,
//   households: [single, couple, family4],
// };

// ── pure helpers (exported so the Vitest suites can import & assert them) ──

/** Sum the monthly amounts of a set of line items. */
export function sumLineItems(items: LineItem[]): Money {
  return items.reduce((total, item) => total + item.amount, 0);
}

/**
 * Shortfall = total income − total essential costs. Negative → deficit
 * (status/red styling on the client).
 *
 * Labelling caveat: `costs` is currently food-only while `income` includes a
 * housing/rental line earmarked for rent, so this value is "what's left AFTER
 * healthy food, for rent + heat + everything else", NOT a disposable surplus.
 * The UI must frame it that way, never a bare "money left".
 */
export function computeShortfall(income: LineItem[], costs: LineItem[]): Money {
  return sumLineItems(income) - sumLineItems(costs);
}

/** Convenience lookup by household id. */
export function getHousehold(
  data: GraphData,
  id: HouseholdId,
): Household | undefined {
  return data.households.find((h) => h.id === id);
}

/** Deep income poverty threshold: below 75% of the Market Basket Measure line. */
export const DEEP_POVERTY_FRACTION = 0.75;

/**
 * A household's total income as a share of its own MBM poverty line (1 = at the
 * line). This is the axis of the cross-household comparison chart and mirrors
 * Maytree's "welfare income vs. the Market Basket Measure" framing: the income
 * total includes the rent-earmarked housing benefit, exactly as Maytree counts
 * total welfare income. Returns 0 when the line is non-positive (guards ÷0).
 */
export function povertyLineShare(household: Household): number {
  if (household.povertyLineMonthly <= 0) return 0;
  return sumLineItems(household.income) / household.povertyLineMonthly;
}

/**
 * Count, across the modelled households, how many fall below the MBM poverty line
 * and how many are in *deep* poverty (< 75% of the line). Derived, never hardcoded,
 * so the on-page poverty claim can't drift from the households actually shown.
 * Exported for the Sources & methodology copy and for tests.
 */
export function povertyStats(households: Household[]): {
  total: number;
  belowLine: number;
  deepPoverty: number;
} {
  const belowLine = households.filter(
    (h) => sumLineItems(h.income) < h.povertyLineMonthly,
  ).length;
  const deepPoverty = households.filter(
    (h) =>
      sumLineItems(h.income) < DEEP_POVERTY_FRACTION * h.povertyLineMonthly,
  ).length;
  return { total: households.length, belowLine, deepPoverty };
}
