/**
 * NL Eats, committed seed snapshot (server-only).
 *
 * `data/graph-data.csv` is the SINGLE committed copy of the dataset: a snapshot
 * of the Google Sheet (the source of truth) regenerated by `npm run sync:data`,
 * never hand-edited. This module parses it into the fixed `GraphData` shape and
 * is the one in-repo derivation of the baseline, used for:
 *   • the offline / Sheet-unreachable fallback (`lib/load-graph-data.ts`);
 *   • the server-rendered sources section (`app/page.tsx`);
 *   • the Vitest suites (which formerly imported the hand-typed `mockGraphData`).
 *
 * It uses `node:fs` and MUST only be imported by server code or tests, never a
 * client component, so `papaparse` never enters the client bundle. (This is why
 * it lives here and not in `lib/graph-data.ts`, which clients import for types
 * and pure helpers.)
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { parseGraphDataCsv } from "@/lib/parse-sheet-csv";
import type { GraphData } from "@/lib/graph-data";

/**
 * Resolve the committed CSV's path. Keeping the `new URL(<literal>,
 * import.meta.url)` form lets Next's file-tracing bundle the CSV into the
 * deployed function so it's present at runtime. Under jsdom (component tests)
 * `import.meta.url` is an http URL, not `file:`, so fall back to `process.cwd()`.
 */
function seedCsvPath(): string {
  const url = new URL("../data/graph-data.csv", import.meta.url);
  return url.protocol === "file:"
    ? fileURLToPath(url)
    : join(process.cwd(), "data/graph-data.csv");
}

/** Read + parse the committed seed CSV into `GraphData`. Throws if it can't parse. */
function readSeed(): GraphData {
  return parseGraphDataCsv(readFileSync(seedCsvPath(), "utf8"));
}

let cached: GraphData | null = null;

/**
 * The committed seed dataset (memoized). The CSV is a static build input, so a
 * single parse per process is enough. Callers must not mutate the returned object
 * (the Route Handler shallow-clones before adding `meta.stale`).
 */
export function getSeedGraphData(): GraphData {
  return (cached ??= readSeed());
}
