/**
 * NL Eats, committed seed snapshot (server-only).
 *
 * `data/graph-data.csv` is the SINGLE committed copy of the dataset: a snapshot
 * of the Google Sheet (the source of truth) regenerated by `npm run sync:data`,
 * never hand-edited. This module parses it into the fixed `GraphData` shape and
 * is the one in-repo derivation of the baseline, used for:
 *   • the offline / Sheet-unreachable fallback (`lib/load-graph-data.ts`);
 *   • the server-rendered sources section (`app/(site)/sources/page.tsx`);
 *   • the Vitest suites.
 *
 * The CSV is consumed as a BUNDLED STRING (`lib/graph-data-snapshot.ts`, generated
 * from the CSV by `scripts/gen-seed-snapshot.mjs`), not read from disk at runtime.
 * A production Turbopack build compiles `readFileSync(new URL(..., import.meta.url))`
 * into a Turbopack asset-URL read out of `.next/server/assets/`, and that path does
 * not survive Netlify's serverless-function packaging, so the read throws ENOENT and
 * the data route 502s (works locally, fails on deploy). Inlining the CSV as a string
 * keeps it in the JS bundle on every host and builder, so the function never touches
 * the filesystem. The drift guard in `lib/seed-data.test.ts` keeps the generated
 * snapshot identical to `data/graph-data.csv`.
 *
 * It uses `papaparse` (via `parseGraphDataCsv`) and MUST only be imported by server
 * code or tests, never a client component, so `papaparse` never enters the client
 * bundle. (This is why it lives here and not in `lib/graph-data.ts`, which clients
 * import for types and pure helpers.)
 */

import { parseGraphDataCsv } from "@/lib/parse-sheet-csv";
import { graphDataCsv } from "@/lib/graph-data-snapshot";
import type { GraphData } from "@/lib/graph-data";

let cached: GraphData | null = null;

/**
 * The committed seed dataset (memoized). The CSV is a static build input, so a
 * single parse per process is enough. Callers must not mutate the returned object
 * (the Route Handler shallow-clones before adding `meta.stale`).
 */
export function getSeedGraphData(): GraphData {
  return (cached ??= parseGraphDataCsv(graphDataCsv));
}
